### ISSUE TITLE
Diagrams as code 

### ISSUE THREAD

**Issue by tomaszbarwicki** [eclipse-tractusx/sldt-discovery-finder#113]
Hi team,

There is a number of diagrams in sldt-discovery-finder/docs/media repository stored as .png files. I could find existing .drawio schemas for some, but not for all though.
Please consider ahering to [TRG 1.04](https://eclipse-tractusx.github.io/docs/release/trg-1/trg-1-4/), describing the process of creation and modification / change to other suggested methods.

Updates https://github.com/eclipse-tractusx/sldt-discovery-finder/issues/110

**Comment by tunacicek** [comment]
We will migrated our existing diagrams in the current release (2024.05).

**Comment by tunacicek** [comment]
PR is created: 
https://github.com/eclipse-tractusx/sldt-discovery-finder/pull/126

**Comment by tunacicek** [comment]
PR merged. Diagrams migrated in mermaid. We can close this issue.
