### ISSUE TITLE
Fix default password exposure for dataSource

### ISSUE THREAD

**Issue by tomaszbarwicki** [eclipse-tractusx/sldt-discovery-finder#114]
Issue related to password exposure at [values.yaml](https://github.com/eclipse-tractusx/sldt-discovery-finder/blob/main/charts/discoveryfinder/values.yaml#L64 in dataSource section. The password seems to be used in specific condition when enablePostgres is set to false.

Recommendation is to provide description/explanation in comments to set the user/password manually configuring data source. Ensure no default passwords are set in the values.yaml following per best practice.

Updates https://github.com/eclipse-tractusx/sldt-discovery-finder/issues/110

**Comment by tunacicek** [comment]
fixed and merged.
