### ISSUE TITLE
Incorrect copyright headers years range

### ISSUE THREAD

**Issue by tomaszbarwicki** [eclipse-tractusx/sldt-discovery-finder#118]
Please correct copyright headers years range in the files across repository.

some examples:

https://github.com/eclipse-tractusx/sldt-discovery-finder/blob/main/backend/src/main/resources/static/discovery-finder-openapi.yaml

https://github.com/eclipse-tractusx/sldt-discovery-finder/blob/main/backend/pom.xml

https://github.com/eclipse-tractusx/sldt-discovery-finder/blob/main/backend/src/main/resources/db/changelog/db.changelog-extensions.yaml

More details: https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-02
Updates https://github.com/eclipse-tractusx/sldt-discovery-finder/issues/110

**Comment by tunacicek** [comment]
Hi @tomaszbarwicki , 
PR is created. 
https://github.com/eclipse-tractusx/sldt-discovery-finder/pull/119
