### ISSUE TITLE
QG4: TRG 5.02 - Chart structure

### ISSUE THREAD

**Issue by tomaszbarwicki** [eclipse-tractusx/sldt-discovery-finder#32]
Helm Chart Version: 0.1.5
App Version: 0.2.2-M1

1. Following files missing in the chart structure:

charts/discoveryfinder/LICENSE
charts/discoveryfinder/README.md

2. Not all files contain copyright & license header
i.e. charts/discoveryfinder/templates/ConfigMap.yaml
charts/discoveryfinder/templates/deployment.yaml

3. The .helmignore file should contain as a minimal set the following entries:

values?*.yaml
values?*.yml

You can find more information and examples [HERE](https://eclipse-tractusx.github.io/docs/release/trg-5/trg-5-02)

**Comment by bs-sili** [comment]
Hi @tomaszbarwicki,

we updated the helm charts structure with this PR: https://github.com/eclipse-tractusx/sldt-discovery-finder/pull/42

**Comment by tomaszbarwicki** [comment]
thanks @bs-sili looks good to me, I understand that there will be a new release with all the TRG fixes?

**Comment by bs-sili** [comment]
Hi @tomaszbarwicki ,
many thanks for your feedback. If it is fine, please close that issue. Yes, you are right, we want to create a new image for the release when all TRG fixes are fine. So please provide us a feedback when everything is done. Many thanks!
