### ISSUE TITLE
QG4: TRG 5.04 - Resource Management

### ISSUE THREAD

**Issue by tomaszbarwicki** [eclipse-tractusx/sldt-discovery-finder#33]
Helm Chart Version: 0.1.5
App Version: 0.2.2-M1

[Resources](https://github.com/eclipse-tractusx/sldt-discovery-finder/blob/980b510871b519581869af4028c1e9a5a3c3faf6/charts/discoveryfinder/values.yaml#L67-L71) section used in the values.yaml for your [Deployment](https://github.com/eclipse-tractusx/sldt-discovery-finder/blob/v0.2.2-M1/charts/discoveryfinder/templates/deployment.yaml) doesn't comply with TRG 5.04:
1. No CPU resources configuration in Requests & Limits
2. Memory not equal in Requests & Limits

You can find more information and examples [HERE](https://eclipse-tractusx.github.io/docs/release/trg-5/trg-5-04)

Updates https://github.com/eclipse-tractusx/sldt-discovery-finder/issues/29

**Comment by bs-sili** [comment]
Hi @tomaszbarwicki ,
we integrated this with PR "Resource management settings adjusted #47". If it is fine, please close that issue. Many thanks!

**Comment by tomaszbarwicki** [comment]
Hi @bs-sili, as mentioned looks better, however I'd recommend to differentiate CPU values for requests and limits as TRG 5.04 suggests. I'd advise also to use Grafana dashboard to determine realistic CPU requirements of the app.

**Comment by bs-sili** [comment]
Hi @tomaszbarwicki,
i corrected the values for the cpu for request and limit and I made a PR for that issue: https://github.com/eclipse-tractusx/sldt-discovery-finder/pull/48

**Comment by tomaszbarwicki** [comment]
LGTM
