### ISSUE TITLE
QG4: TRG 5.09 - Helm test 

### ISSUE THREAD

**Issue by tomaszbarwicki** [eclipse-tractusx/sldt-discovery-finder#34]
Helm Chart Version: 0.1.5
App Version: 0.2.2-M1

Unable to find and verify implementation of helm test solution as per [TRG 5.09](
https://eclipse-tractusx.github.io/docs/release/trg-5/trg-5-09).

Updates https://github.com/eclipse-tractusx/sldt-discovery-finder/issues/29

**Comment by bs-sili** [comment]
Hi @tomaszbarwicki,

we integrated the Helm test with PR "Feat: Added Helm test #46". Please close that issue, if it is fine. Many thanks!

**Comment by bs-sili** [comment]
Hi @tomaszbarwicki , 

we made the changes with PR https://github.com/eclipse-tractusx/sldt-discovery-finder/pull/49 and also merged. So if it is fine, please close that issue.

**Comment by tomaszbarwicki** [comment]
LGTM
