### ISSUE TITLE
QG4: TRG 5.11 Upgradeability

### ISSUE THREAD

**Issue by tomaszbarwicki** [eclipse-tractusx/sldt-discovery-finder#35]
Helm Chart Version: 0.1.5
App Version: 0.2.2-M1

Recommend to implement GitHub workflow to test helm chart upgradeability of the application.
More information you can find [HERE](https://eclipse-tractusx.github.io/docs/release/trg-5/trg-5-11).

Manual local test from 0.1.4 to 0.1.5 was successful hence marking the check as completed.

**Comment by bs-sili** [comment]
Hi @tomaszbarwicki,
many thanks for testing. If this fine now, please close that issue. Many thanks!
