### ISSUE TITLE
QG4: TRG 7.05 - Legal information for distributions

### ISSUE THREAD

**Issue by tomaszbarwicki** [eclipse-tractusx/sldt-discovery-finder#36]
Helm Chart Version: 0.1.5
App Version: 0.2.2-M1

Not found required files in the .jar artefact.
License, notice and DEPENDENCIES files, must be included in the root of every distribution artifact (e.g. JAR file).

More information you can find [HERE](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-05/).

**Comment by tunacicek** [comment]
@tomaszbarwicki is done. We build a new image. Can you check it again?

**Comment by tomaszbarwicki** [comment]
thank you @tunacicek, does that mean the fix is in v0.2.3-M1 and that will go to release 3.2?

**Comment by tunacicek** [comment]
@tomaszbarwicki , 
yes the version 0.2.3-M1 includes in the jar files the required files like LICENSE, NOTICE and DEPENDENCIES. 
And this version is for release 3.2
