### ISSUE TITLE
Description / Test

### ISSUE THREAD

**Issue by bs-sili** [eclipse-tractusx/sldt-discovery-finder#63]
This is a test

https://github.com/eclipse-tractusx/sig-release/issues/347

**Comment by RazvanZmau** [comment]
![image](https://github.com/eclipse-tractusx/sldt-discovery-finder/assets/147802975/0afb24e7-4384-45f8-a52f-a73439af3c8e)

**Comment by RazvanZmau** [comment]
![test Fabian](https://github.com/eclipse-tractusx/sldt-discovery-finder/assets/147802975/a05671c2-107e-43d2-8f80-40b3c9988d82)

**Comment by RazvanZmau** [comment]
![test Fabian](https://github.com/eclipse-tractusx/sldt-discovery-finder/assets/147802975/bb736bb3-7743-4e2d-a21a-16d0e426106f)

**Comment by RazvanZmau** [comment]
![test Fabian](https://github.com/eclipse-tractusx/sldt-discovery-finder/assets/147802975/a90e8aa0-4f07-4695-bd58-6b79c0995cca)
