### ISSUE TITLE
QG 4 checks (Release 12.23)

### ISSUE THREAD

**Issue by tomaszbarwicki** [eclipse-tractusx/sldt-discovery-finder#64]
## QG checks
Please keep this issue open until QG is concluded and will be managed by the Issue Creator!
We will inform you about finding and proposals in separated issues, this issue here is for the Overview of the Checks!

### Please keep this issue open until QG is concluded!

Product Owner: Thomas Henn
Dev SPOC: Tunahan Cicek / Sahil Aggarwal (@agg3fe) / Simone Lindner (@bs-sili )
Helm Chart Version: 0.1.12
App Version: 0.2.5

### Check of Tractus-X Release Guidelines

- Currently implemented automatic checks can be found under your product on our [Release Guidelines Checks Board](https://eclipse-tractusx.github.io/sig-release/) 
- This QG Check is depending on the mandatory information from our current [Release Guidelines](https://eclipse-tractusx.github.io/docs/release)

#### TRG 1 Documentation

- [x] [TRG 1.01](https://eclipse-tractusx.github.io/docs/release/trg-1/trg-1-1) appropriate `README.md` 
- [x] [TRG 1.02](https://eclipse-tractusx.github.io/docs/release/trg-1/trg-1-2) appropriate install instructions either `INSTALL.md` or in `README.md`
- [x] [TRG 1.03](https://eclipse-tractusx.github.io/docs/release/trg-1/trg-1-3) appropriate `CHANGELOG.md`

[back on top](#qg-checks)

#### TRG 2 Git

- [x] [TRG 2.01](https://eclipse-tractusx.github.io/docs/release/trg-2/trg-2-1) default branch is named `main`
- [x] [TRG 2.03](https://eclipse-tractusx.github.io/docs/release/trg-2/trg-2-3) repository structure
- [x] [TRG 2.04](https://eclipse-tractusx.github.io/docs/release/trg-2/trg-2-4) leading product repository
- [x] [TRG 2.05](https://eclipse-tractusx.github.io/docs/release/trg-2/trg-2-5) `.tractusx` metafile in a proper format

[back on top](#qg-checks)

#### TRG 3 Kubernetes

- [x] [TRG 3.02](https://eclipse-tractusx.github.io/docs/release/trg-3/trg-3-2) persistent volume and persistent volume claim is used when needed

[back on top](#qg-checks)

#### TRG 4 Container

- [x] [TRG 4.01](https://eclipse-tractusx.github.io/docs/release/trg-4/trg-4-1) [semantic versioning](https://semver.org/) and tagging 
- [x] [TRG 4.02](https://eclipse-tractusx.github.io/docs/release/trg-4/trg-4-2) top level `README.md` file or separate `README.md` file for DockerHub, that contains information about the used base image   
- [x] [TRG 4.03](https://eclipse-tractusx.github.io/docs/release/trg-4/trg-4-3) image has `USER` command and Non Root Container
- [x] [TRG 4.05](https://eclipse-tractusx.github.io/docs/release/trg-4/trg-4-05) released image must be placed in `DockerHub`, remove `GHCR` references 
- [x] [TRG 4.06](https://eclipse-tractusx.github.io/docs/release/trg-4/trg-4-06) notice file for `DockerHub` has all necessary information

[back on top](#qg-checks)

#### TRG 5 Helm

- [x] [TRG 5.01](https://eclipse-tractusx.github.io/docs/release/trg-5/trg-5-01) Helm chart must be released
- [x] [TRG 5.02](https://eclipse-tractusx.github.io/docs/release/trg-5/trg-5-02) Helm chart location in `/charts` directory and correct structure
- [x] [TRG 5.04](https://eclipse-tractusx.github.io/docs/release/trg-5/trg-5-04) CPU / MEM resource requests and limits and are properly set
- [x] #68
- [x] [TRG 5.07](https://eclipse-tractusx.github.io/docs/release/trg-5/trg-5-07) Dependencies are present and properly configured in the Chart.yaml
- [x] [TRG 5.08](https://eclipse-tractusx.github.io/docs/release/trg-5/trg-5-08) Product has a single deployable helm chart that contains all components 
- [x] [TRG 5.09](https://eclipse-tractusx.github.io/docs/release/trg-5/trg-5-09) Helm Test running properly
- [x] [TRG 5.10](https://eclipse-tractusx.github.io/docs/release/trg-5/trg-5-10) Products need to support 3 versions at a time
- [x] [TRG 5.11](https://eclipse-tractusx.github.io/docs/release/trg-5/trg-5-11) Upgradeability

[back on top](#qg-checks)
 
#### TRG 6 Released Helm Chart

- [x] [TRG 6.01](https://eclipse-tractusx.github.io/docs/release/trg-6/trg-6-1) Released Helm Chart 

[back on top](#qg-checks)

#### TRG 7 Open Source Governance
- [x] [TRG 7.01](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-01) Legal Documentation
- [x] [TRG 7.02](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-02) License and copyright header  
- [x] [TRG 7.03](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-03) IP checks for project content 
- [x] [TRG 7.04](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-04) IP checks for 3rd party content
- [x] [TRG 7.05](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-05) Legal information for distributions
- [x] [TRG 7.06](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-06) Legal information for end user content
- [x] [TRG 7.07](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-07) Legal notice for documentation

[back on top](#qg-checks)

**Comment by tomaszbarwicki** [comment]
Hi @bs-sili , @tunacicek this is a QG 4 issue created for source code.

Can you please confirm below:

  > Product Owner: Thomas Henn
  > Dev SPOC: Tunahan Cicek / Sahil Aggarwal (@agg3fe)

and provide following versions for which the check needs to be performed:

  > Helm Chart Version:
  > App Version: 


Thank you in advance.

**Comment by tomaszbarwicki** [comment]
Hey @tunacicek, @agg3fe I'm a bit not clear on the CHANGELOG.md which is detailing latest version 2.6.0 however I can't actually find it released, can you help me with that?

**Comment by agg3fe** [comment]
> Hey @tunacicek, @agg3fe I'm a bit not clear on the CHANGELOG.md which is detailing latest version 2.6.0 however I can't actually find it released, can you help me with that?

@tomaszbarwicki, yes actually 2.6.0 is not required in CHANGELOG.md, there was a small mistake from our side. I will clean the changelog.md now.

**Comment by agg3fe** [comment]
> > Hey @tunacicek, @agg3fe I'm a bit not clear on the CHANGELOG.md which is detailing latest version 2.6.0 however I can't actually find it released, can you help me with that?
> 
> @tomaszbarwicki, yes actually 2.6.0 is not required in CHANGELOG.md, there was a small mistake from our side. I will clean the changelog.md now.

We have cleaned the changelog.md file.

**Comment by tomaszbarwicki** [comment]
> > > Hey @tunacicek, @agg3fe I'm a bit not clear on the CHANGELOG.md which is detailing latest version 2.6.0 however I can't actually find it released, can you help me with that?
> > 
> > 
> > @tomaszbarwicki, yes actually 2.6.0 is not required in CHANGELOG.md, there was a small mistake from our side. I will clean the changelog.md now.
> 
> We have cleaned the changelog.md file.

Thanks @agg3fe, are you able to provide following info: https://github.com/eclipse-tractusx/sldt-discovery-finder/issues/64#issuecomment-1818514358

**Comment by bs-sili** [comment]
Hi @tomaszbarwicki,

Product Owner: Thomas Henn
Dev SPOC: Tunahan Cicek / Sahil Aggarwal (@agg3fe) / Simone Lindner (@bs-sili )
Helm Chart Version: 0.1.12
App Version: 0.2.5

**Comment by tomaszbarwicki** [comment]
> Hi @tomaszbarwicki,
> 
> thank you for creating already a PR for the missing copyright header in tractusx file. Is this QG blocking or can we update this file after QG?

Hi @bs-sili,
It's my recommendation to fully comply with the TRGs, wouldn't call it a blocker though. However the other PR I raised for helm workflow would be necessary for me to test installation on different k8s versions and upgradeability of the helm chart.

**Comment by tomaszbarwicki** [comment]
Thank you for cooperation, QG4 checks approved.
