### ISSUE TITLE
Insecure password exposure in values.yaml

### ISSUE THREAD

**Issue by tomaszbarwicki** [eclipse-tractusx/sldt-discovery-finder#68]
Creating issue related to hardcoded password in the values.yaml file:

At line https://github.com/eclipse-tractusx/sldt-discovery-finder/blob/0eb0393a89a54fce25655a062e57119a5642f483/charts/discoveryfinder/values.yaml#L85C1-L85C1 password is set to 'password'. Suggest to use existing postgresql secret with auto-generated password.

updates #https://github.com/eclipse-tractusx/sldt-discovery-finder/issues/64

**Comment by bs-sili** [comment]
Hi @tomaszbarwicki,

is this QG relevant or can it solved after QG?
At the moment we have a ticket about that topic created for another application. We are also already in contact with the DevSecOps team about that topic.

**Comment by tomaszbarwicki** [comment]
Hi @bs-sili, yes, let's fix it afterwards.

**Comment by drhansbeck** [comment]
Hi @bs-sili , @tomaszbarwicki , 

great spotting of the plain-text password! There's another one in the same file:
https://github.com/eclipse-tractusx/sldt-discovery-finder/blob/0eb0393a89a54fce25655a062e57119a5642f483/charts/discoveryfinder/values.yaml#L53-L54
