### ISSUE TITLE
[TRG Checks] Insecure password exposure in values.yaml

### ISSUE THREAD

**Issue by RazvanZmau** [eclipse-tractusx/sldt-discovery-finder#85]
<html>
<body>
<p style="margin: 0px; padding: 0px; color: rgb(23, 43, 77); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, Oxygen, Ubuntu, &quot;Fira Sans&quot;, &quot;Droid Sans&quot;, &quot;Helvetica Neue&quot;, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">For TRG Checks of the Discovery Finder we have got this issue:</p><p style="margin: 10px 0px 0px; padding: 0px; color: rgb(23, 43, 77); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, Oxygen, Ubuntu, &quot;Fira Sans&quot;, &quot;Droid Sans&quot;, &quot;Helvetica Neue&quot;, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><a href="https://github.com/eclipse-tractusx/sldt-discovery-finder/issues/68" class="external-link" target="_blank" rel="nofollow noopener" title="Follow link" style="color: rgb(0, 82, 204); text-decoration: var(--aui-link-decoration); cursor: pointer;">https://github.com/eclipse-tractusx/sldt-discovery-finder/issues/68</a></p><p style="margin: 10px 0px 0px; padding: 0px; color: rgb(23, 43, 77); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, Oxygen, Ubuntu, &quot;Fira Sans&quot;, &quot;Droid Sans&quot;, &quot;Helvetica Neue&quot;, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"> </p><div class="table-wrap" style="margin: 0px; padding: 0px; color: rgb(23, 43, 77); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, Oxygen, Ubuntu, &quot;Fira Sans&quot;, &quot;Droid Sans&quot;, &quot;Helvetica Neue&quot;, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
Creating issue related to hardcoded password in the values.yaml file:At line https://github.com/eclipse-tractusx/sldt-discovery-finder/blob/0eb0393a89a54fce25655a062e57119a5642f483/charts/discoveryfinder/values.yaml#L85C1-L85C1 password is set to 'password'. Suggest to use existing postgresql secret with auto-generated password.updates ##64
--

</div>
</body>
</html>For TRG Checks of the Discovery Finder we have got this issue:

https://github.com/eclipse-tractusx/sldt-discovery-finder/issues/68

 

Creating issue related to hardcoded password in the values.yaml file:
At line https://github.com/eclipse-tractusx/sldt-discovery-finder/blob/0eb0393a89a54fce25655a062e57119a5642f483/charts/discoveryfinder/values.yaml#L85C1-L85C1 password is set to 'password'. Suggest to use existing postgresql secret with auto-generated password.
updates #[#64](https://github.com/eclipse-tractusx/sldt-discovery-finder/issues/64)

**Comment by thomas-henn** [comment]
https://github.com/eclipse-tractusx/sig-release/issues/347
